version: "3.7"

volumes:
  esdata:
    driver: local
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elastic
    environment:
      - node.name=elastic
      - cluster.name=es-docker-cluster
      # - discovery.seed_hosts=elastic02
      - cluster.initial_master_nodes=elastic
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    privileged: true
    tty: true
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/local/var/lib/elasticsearch
  chirpbird:
    image: 978879/chirpbird978879
    container_name: chirpbird
    build: .
    restart: on-failure
    environment:
        PORT: 4000
    ports:
      - 4000:4000
  chirpbird-client:
    image: 978879/chirpbird-client
    container_name: chirpbird-client
    environment:
      REACT_MASTER_APP_URL: chirpbird
    ports:
      - 3000:80
